apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: api-gateway
  name: api-gateway
spec:
  replicas: 1
  minReadySeconds: 30
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 25%
  selector:
    matchLabels:
      io.kompose.service: api-gateway
  template:
    metadata:
      labels:
        io.kompose.service: api-gateway
    spec:
      containers:
      - command:
        - ./dockerize
        - -wait=tcp://discovery-server:8761
        - -timeout=60s
        - --
        - java
        - -XX:+UnlockExperimentalVMOptions
        - -XX:+UseCGroupMemoryLimitForHeap
        - -Djava.security.egd=file:/dev/./urandom
        - -Dspring.profiles.active=docker
#        - -Deureka.instance.preferIpAddress=true
        - -Deureka.instance.hostname=api-gateway
        - -jar
        - /app.jar
        image: spring-petclinic-api-gateway
        name: api-gateway
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "536870912"
      restartPolicy: Always

