apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: admin-server
  name: admin-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: admin-server
  template:
    metadata:
      labels:
        io.kompose.service: admin-server
    spec:
      containers:
      - command:
        - ./dockerize
        - -wait=tcp://discovery-server:8761
        - -timeout=60s
        - --
        - java
        - -XX:+UnlockExperimentalVMOptions
        - -XX:+UseCGroupMemoryLimitForHeap
        - -Djava.security.egd=file:/dev/./urandom
        - -jar
        - /app.jar
        image: spring-petclinic-admin-server
        name: admin-server
        ports:
        - containerPort: 9090
        resources:
          limits:
            memory: "536870912"
      restartPolicy: Always
